# Generated by Django 6.0.6 on 2026-07-02 14:24

import courrier.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True, verbose_name='Nom')),
                ('type', models.CharField(choices=[('INSTITUTION_PUBLIQUE', 'Institution publique'), ('PARTENAIRE_INTERNATIONAL', 'Partenaire international'), ('BANQUE', 'Banque'), ('ENTREPRISE', 'Entreprise'), ('PARTICULIER', 'Particulier'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30, verbose_name='Type')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Correspondant',
                'verbose_name_plural': 'Correspondants',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=100, verbose_name='Libellé')),
                ('sens', models.CharField(choices=[('ARRIVEE', 'Arrivée'), ('DEPART', 'Départ')], max_length=10, verbose_name='Sens')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Registre',
                'verbose_name_plural': 'Registres',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordre', models.CharField(editable=False, max_length=30, unique=True, verbose_name="Numéro d'ordre")),
                ('sens', models.CharField(choices=[('ARRIVEE', 'Arrivée'), ('DEPART', 'Départ')], default='ARRIVEE', max_length=10, verbose_name='Sens')),
                ('date_document', models.DateField(verbose_name='Date du document')),
                ('date_arrivee', models.DateField(default=datetime.date.today, verbose_name="Date d'arrivée")),
                ('objet', models.CharField(max_length=500, verbose_name='Objet')),
                ('confidentialite', models.CharField(choices=[('ORDINAIRE', 'Ordinaire'), ('CONFIDENTIEL', 'Confidentiel')], default='ORDINAIRE', max_length=15, verbose_name='Confidentialité')),
                ('nombre_pieces', models.PositiveSmallIntegerField(default=1, verbose_name='Nombre de pièces')),
                ('delai_reponse', models.DateField(blank=True, null=True, verbose_name='Délai de réponse')),
                ('statut', models.CharField(choices=[('ENREGISTRE', 'Enregistré'), ('IMPUTE', 'Imputé'), ('EN_TRAITEMENT', 'En traitement'), ('TRAITE', 'Traité'), ('CLASSE', 'Classé sans suite')], default='ENREGISTRE', max_length=15, verbose_name='Statut')),
                ('scan', models.FileField(blank=True, null=True, upload_to=courrier.models.chemin_scan, verbose_name='Scan (PDF)')),
                ('hash_sha256', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Empreinte SHA-256')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('correspondant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers', to='courrier.correspondant')),
                ('courrier_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='courrier.courrier')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers_enregistres', to=settings.AUTH_USER_MODEL)),
                ('registre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courriers', to='courrier.registre')),
            ],
            options={
                'verbose_name': 'Courrier',
                'verbose_name_plural': 'Courriers',
                'ordering': ['-date_arrivee', '-numero_ordre'],
                'permissions': [('enregistrer_courrier', 'Peut enregistrer un courrier'), ('modifier_courrier', 'Peut modifier un courrier'), ('consulter_courrier', 'Peut consulter les courriers'), ('consulter_confidentiel', 'Peut consulter les courriers confidentiels'), ('classer_courrier', 'Peut classer un courrier sans suite')],
            },
        ),
        migrations.CreateModel(
            name='EvenementCourrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENREGISTREMENT', 'Enregistrement'), ('MODIFICATION', 'Modification'), ('REMPLACEMENT_SCAN', 'Remplacement du scan'), ('CLASSEMENT', 'Classement sans suite')], max_length=20, verbose_name='Type')),
                ('horodatage', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements_courrier', to=settings.AUTH_USER_MODEL)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='courrier.courrier')),
            ],
            options={
                'verbose_name': 'Événement de courrier',
                'verbose_name_plural': 'Événements de courrier',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='CompteurRegistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('dernier_numero', models.PositiveIntegerField(default=0, verbose_name='Dernier numéro')),
                ('registre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compteurs', to='courrier.registre')),
            ],
            options={
                'verbose_name': 'Compteur de registre',
                'verbose_name_plural': 'Compteurs de registre',
                'ordering': ['registre', '-annee'],
                'unique_together': {('registre', 'annee')},
            },
        ),
    ]
