# Generated by Django 6.0.6 on 2026-07-03 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('courrier', '0002_seed_referentiels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courrier',
            options={'ordering': ['-date_arrivee', '-numero_ordre'], 'permissions': [('enregistrer_courrier', 'Peut enregistrer un courrier'), ('modifier_courrier', 'Peut modifier un courrier'), ('consulter_courrier', 'Peut consulter les courriers'), ('consulter_confidentiel', 'Peut consulter les courriers confidentiels'), ('classer_courrier', 'Peut classer un courrier sans suite'), ('imputer_premier_niveau', 'Peut imputer un courrier au premier niveau'), ('imputer_sous_arbre', 'Peut sous-imputer dans son sous-arbre'), ('accuser_reception', "Peut accuser réception d'une imputation"), ('marquer_traite', 'Peut marquer une imputation traitée')], 'verbose_name': 'Courrier', 'verbose_name_plural': 'Courriers'},
        ),
        migrations.AlterField(
            model_name='evenementcourrier',
            name='type',
            field=models.CharField(choices=[('ENREGISTREMENT', 'Enregistrement'), ('MODIFICATION', 'Modification'), ('REMPLACEMENT_SCAN', 'Remplacement du scan'), ('CLASSEMENT', 'Classement sans suite'), ('IMPUTATION', 'Imputation'), ('SOUS_IMPUTATION', 'Sous-imputation'), ('ACCUSE_RECEPTION', 'Accusé de réception'), ('MARQUE_TRAITE', 'Marqué traité'), ('RETOUR_IMPUTATION', "Annulation d'imputation")], max_length=20, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Imputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(choices=[('POUR_TRAITEMENT', 'Pour traitement'), ('POUR_AVIS', 'Pour avis'), ('POUR_INFORMATION', 'Pour information'), ('POUR_ATTRIBUTION', 'Pour attribution'), ('M_EN_PARLER', "M'en parler")], max_length=20, verbose_name='Instruction')),
                ('delai', models.DateField(blank=True, null=True, verbose_name='Délai')),
                ('commentaire', models.CharField(blank=True, max_length=500, verbose_name='Commentaire')),
                ('date_imputation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('accuse_le', models.DateTimeField(blank=True, null=True, verbose_name='Accusé le')),
                ('traite_le', models.DateTimeField(blank=True, null=True, verbose_name='Traité le')),
                ('commentaire_traitement', models.CharField(blank=True, max_length=500, verbose_name='Commentaire de traitement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE_ACCUSE', "En attente d'accusé"), ('ACCUSEE', 'Accusée'), ('TRAITEE', 'Traitée')], default='EN_ATTENTE_ACCUSE', max_length=20, verbose_name='Statut')),
                ('annulee_le', models.DateTimeField(blank=True, null=True, verbose_name='Annulée le')),
                ('accuse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imputations_accusees', to=settings.AUTH_USER_MODEL)),
                ('annulee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imputations_annulees', to=settings.AUTH_USER_MODEL)),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputations', to='courrier.courrier')),
                ('direction_cible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputations', to='comptes.direction')),
                ('imputation_mere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_imputations', to='courrier.imputation')),
                ('impute_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputations_faites', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imputations_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imputation',
                'verbose_name_plural': 'Imputations',
                'ordering': ['date_imputation', 'id'],
            },
        ),
    ]
