# Generated by Django 6.0.6 on 2026-07-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courrier', '0004_seed_groupes_c2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courrier',
            options={'ordering': ['-date_arrivee', '-numero_ordre'], 'permissions': [('enregistrer_courrier', 'Peut enregistrer un courrier'), ('modifier_courrier', 'Peut modifier un courrier'), ('consulter_courrier', 'Peut consulter les courriers'), ('consulter_confidentiel', 'Peut consulter les courriers confidentiels'), ('classer_courrier', 'Peut classer un courrier sans suite'), ('imputer_premier_niveau', 'Peut imputer un courrier au premier niveau'), ('imputer_sous_arbre', 'Peut sous-imputer dans son sous-arbre'), ('accuser_reception', "Peut accuser réception d'une imputation"), ('marquer_traite', 'Peut marquer une imputation traitée'), ('voir_tableau_bord', 'Peut consulter le tableau de bord de pilotage')], 'verbose_name': 'Courrier', 'verbose_name_plural': 'Courriers'},
        ),
        migrations.AddField(
            model_name='imputation',
            name='derniere_relance_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière relance le'),
        ),
        migrations.AlterField(
            model_name='evenementcourrier',
            name='type',
            field=models.CharField(choices=[('ENREGISTREMENT', 'Enregistrement'), ('MODIFICATION', 'Modification'), ('REMPLACEMENT_SCAN', 'Remplacement du scan'), ('CLASSEMENT', 'Classement sans suite'), ('IMPUTATION', 'Imputation'), ('SOUS_IMPUTATION', 'Sous-imputation'), ('ACCUSE_RECEPTION', 'Accusé de réception'), ('MARQUE_TRAITE', 'Marqué traité'), ('RETOUR_IMPUTATION', "Annulation d'imputation"), ('RELANCE', 'Relance')], max_length=20, verbose_name='Type'),
        ),
    ]
