# Generated by Django 6.0.6 on 2026-07-04 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
        ('courrier', '0006_seed_groupes_c3'),
    ]

    operations = [
        migrations.AddField(
            model_name='courrier',
            name='date_signature',
            field=models.DateField(blank=True, null=True, verbose_name='Date de signature'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='decharge_commentaire',
            field=models.CharField(blank=True, max_length=255, verbose_name='Décharge — commentaire'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='decharge_recue_le',
            field=models.DateField(blank=True, null=True, verbose_name='Décharge reçue le'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='expedie_le',
            field=models.DateField(blank=True, null=True, verbose_name='Expédié le'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='reference_complete',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True, verbose_name='Référence complète'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='signataire_nom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Signataire — nom'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='signataire_qualite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Signataire — qualité'),
        ),
        migrations.AddField(
            model_name='courrier',
            name='structure_emettrice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courriers_emis', to='comptes.direction', verbose_name='Structure émettrice'),
        ),
        migrations.AddField(
            model_name='registre',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registres', to='comptes.direction', verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='evenementcourrier',
            name='type',
            field=models.CharField(choices=[('ENREGISTREMENT', 'Enregistrement'), ('MODIFICATION', 'Modification'), ('REMPLACEMENT_SCAN', 'Remplacement du scan'), ('CLASSEMENT', 'Classement sans suite'), ('IMPUTATION', 'Imputation'), ('SOUS_IMPUTATION', 'Sous-imputation'), ('ACCUSE_RECEPTION', 'Accusé de réception'), ('MARQUE_TRAITE', 'Marqué traité'), ('RETOUR_IMPUTATION', "Annulation d'imputation"), ('RELANCE', 'Relance'), ('CLOTURE_PAR_NIVEAU_SUPERIEUR', 'Clôture par le niveau supérieur'), ('REPONSE_LIEE', 'Réponse liée'), ('CLOTURE_PAR_REPONSE', 'Clôture par réponse'), ('EXPEDITION', 'Expédition'), ('DECHARGE_RECUE', 'Décharge reçue')], max_length=30, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='DestinataireCopie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AMPLIATION', 'Ampliation')], default='AMPLIATION', max_length=20, verbose_name='Type')),
                ('correspondant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ampliations', to='courrier.correspondant')),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='courrier.courrier')),
            ],
            options={
                'verbose_name': 'Destinataire en copie',
                'verbose_name_plural': 'Destinataires en copie',
                'unique_together': {('courrier', 'correspondant')},
            },
        ),
    ]
