# Generated by Django 6.0.6 on 2026-06-30 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrique', models.CharField(choices=[('lois-de-finances', 'Lois de finances'), ('lois-de-reglement', 'Lois de règlement'), ('rapports-execution', "Rapports d'exécution"), ('reformes-budgetaires', 'Réformes budgétaires'), ('rapports-performance', 'Rapports de performance'), ('dppd', 'Programmation pluriannuelle (DPPD)')], db_index=True, max_length=40, verbose_name='Rubrique')),
                ('annee', models.PositiveIntegerField(db_index=True, verbose_name='Année')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('type', models.CharField(blank=True, help_text='Ex. : « Loi de finances initiale », « Rectificative »…', max_length=120, verbose_name='Type')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='budget/', verbose_name='Fichier PDF')),
                ('lien', models.CharField(blank=True, help_text="Utilisé si aucun PDF n'est téléversé. « # » par défaut.", max_length=300, verbose_name='Lien externe')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Document budgétaire',
                'verbose_name_plural': 'Documents budgétaires',
                'ordering': ['-annee', 'ordre', 'id'],
            },
        ),
    ]
