# Generated by Django 6.0.6 on 2026-06-28 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='MINISTÈRE DES FINANCES', max_length=200, verbose_name='Nom du site')),
                ('sous_titre', models.CharField(default='République du Niger', max_length=200, verbose_name='Sous-titre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo (armoiries)')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='X (Twitter)')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('path', models.CharField(blank=True, help_text="Laisser vide pour un menu qui ne sert qu'à regrouper des sous-entrées.", max_length=200, verbose_name='Lien (URL)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='core.menuitem', verbose_name='Menu parent')),
            ],
            options={
                'verbose_name': 'Élément de menu',
                'verbose_name_plural': 'Menu de navigation',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
