# Generated by Django 6.0.6 on 2026-06-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienUtile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé')),
                ('url', models.CharField(default='#', help_text="URL du site. « # » tant que l'adresse n'est pas connue.", max_length=300, verbose_name='Lien')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Lien utile',
                'verbose_name_plural': 'Liens utiles',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('sigle', models.CharField(blank=True, max_length=120, verbose_name='Sigle / description')),
                ('initiales', models.CharField(blank=True, help_text='Affichées dans la pastille si aucun logo. Ex. « FMI ».', max_length=4, verbose_name='Initiales')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires/', verbose_name='Logo')),
                ('url', models.CharField(default='#', max_length=300, verbose_name='Lien')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
