# Generated by Django 6.0.6 on 2026-06-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lienutile_partenaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocReforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiquette', models.CharField(default='Réforme', max_length=60, verbose_name='Étiquette')),
                ('titre', models.CharField(default='Réforme des finances publiques', max_length=200, verbose_name='Titre')),
                ('texte', models.TextField(default="Modernisation de la gestion publique : transparence budgétaire, dématérialisation et conformité aux directives de l'UEMOA (programme PEFA).", verbose_name='Texte')),
                ('bouton_label', models.CharField(default='En savoir plus', max_length=80, verbose_name='Bouton — libellé')),
                ('bouton_url', models.CharField(default='/budget/reformes-budgetaires', max_length=300, verbose_name='Bouton — lien')),
                ('image', models.ImageField(blank=True, help_text='Visuel de fond. Si vide, le champ « URL / chemin » est utilisé.', null=True, upload_to='reforme/', verbose_name='Image')),
                ('image_url', models.CharField(blank=True, default='https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80', max_length=500, verbose_name='Image — URL ou chemin')),
            ],
            options={
                'verbose_name': 'Bloc « Réforme »',
                'verbose_name_plural': 'Bloc « Réforme »',
            },
        ),
    ]
