# Generated by Django 6.0.6 on 2026-06-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=120, verbose_name='Catégorie')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('texte', models.TextField(verbose_name='Texte')),
                ('image', models.ImageField(blank=True, help_text="Visuel officiel. Si vide, l'image de secours est utilisée.", null=True, upload_to='slides/', verbose_name='Image officielle')),
                ('secours', models.URLField(blank=True, help_text="Affichée tant que l'image officielle est absente.", verbose_name='Image de secours (URL)')),
                ('position', models.CharField(blank=True, help_text='Optionnel. Ex. : « center » ou « center top ».', max_length=50, verbose_name='Cadrage')),
                ('cta_label', models.CharField(max_length=120, verbose_name='Bouton — libellé')),
                ('cta_href', models.CharField(max_length=200, verbose_name='Bouton — lien')),
                ('cta_icon', models.CharField(choices=[('arrow', 'Flèche'), ('download', 'Téléchargement')], default='arrow', max_length=10, verbose_name='Bouton — icône')),
                ('cta2_label', models.CharField(blank=True, max_length=120, verbose_name='Bouton 2 — libellé')),
                ('cta2_href', models.CharField(blank=True, max_length=200, verbose_name='Bouton 2 — lien')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Slide (carrousel)',
                'verbose_name_plural': 'Slides (carrousel)',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
