# Generated by Django 6.0.6 on 2026-06-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('icone', models.CharField(choices=[('computer', 'Ordinateur'), ('gavel', 'Marteau (justice / marchés)'), ('account_balance', 'Institution / banque'), ('receipt_long', 'Reçu / impôts'), ('description', 'Document'), ('payments', 'Paiements'), ('public', 'Globe / public'), ('link', 'Lien générique')], default='link', max_length=40, verbose_name='Icône')),
                ('couleur_debut', models.CharField(default='#0a5ca8', help_text='Code hexadécimal, ex. #0a5ca8', max_length=7, verbose_name='Couleur (début)')),
                ('couleur_fin', models.CharField(default='#002B55', help_text='Code hexadécimal, ex. #002B55', max_length=7, verbose_name='Couleur (fin)')),
                ('href', models.CharField(default='#', help_text="URL du service. « # » tant que l'adresse n'est pas connue.", max_length=300, verbose_name='Lien')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Accès rapide',
                'verbose_name_plural': 'Accès rapides',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
