# Generated by Django 6.0.6 on 2026-07-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, help_text='Visuel. Si vide, le champ « URL / chemin » est utilisé.', null=True, upload_to='galerie/', verbose_name='Image')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='Image — URL ou chemin')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos (galerie)',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('duree', models.CharField(blank=True, help_text='Ex. : « 4:35 ».', max_length=12, verbose_name='Durée')),
                ('miniature', models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Miniature')),
                ('miniature_url', models.CharField(blank=True, max_length=500, verbose_name='Miniature — URL ou chemin')),
                ('lien', models.CharField(blank=True, help_text='URL YouTube / MP4. « # » par défaut.', max_length=400, verbose_name='Lien de la vidéo')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
