# Generated by Django 6.0.6 on 2026-06-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Dr Maman Laouali ABDOU RAFA', max_length=200, verbose_name='Nom')),
                ('fonction', models.CharField(default="Ministre de l'Économie et des Finances", max_length=200, verbose_name='Fonction')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ministre/', verbose_name='Photo')),
                ('etiquette', models.CharField(default='Le Ministre', help_text='Petit libellé en haut de la photo.', max_length=60, verbose_name='Étiquette')),
            ],
            options={
                'verbose_name': 'Le Ministre',
                'verbose_name_plural': 'Le Ministre',
            },
        ),
        migrations.CreateModel(
            name='MinistreLien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='Libellé')),
                ('icone', models.CharField(choices=[('menu_book', 'Livre (biographie)'), ('groups', 'Groupe (cabinet)'), ('record_voice_over', 'Discours / voix'), ('description', 'Document'), ('link', 'Lien générique')], default='link', max_length=40, verbose_name='Icône')),
                ('href', models.CharField(default='#', help_text="« # » tant que la page n'existe pas encore.", max_length=300, verbose_name='Lien')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Lien du Ministre',
                'verbose_name_plural': 'Liens du Ministre',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
