# Generated by Django 6.0.6 on 2026-06-29 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministere', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministre',
            name='conseils',
            field=models.TextField(blank=True, help_text='Un sigle par ligne (BCEAO, BOAD, …).', verbose_name="Conseils d'administration"),
        ),
        migrations.AddField(
            model_name='ministre',
            name='conseils_periode',
            field=models.CharField(blank=True, help_text='Ex. : « 2016 – 2021 ».', max_length=60, verbose_name='Conseils — période'),
        ),
        migrations.AddField(
            model_name='ministre',
            name='experience',
            field=models.TextField(blank=True, help_text='Un paragraphe par ligne.', verbose_name='Expérience & expertise'),
        ),
        migrations.AddField(
            model_name='ministre',
            name='nom_complet',
            field=models.CharField(blank=True, help_text='Ex. : « Docteur Maman Laouali ABDOU RAFA ».', max_length=200, verbose_name='Nom complet (biographie)'),
        ),
        migrations.AddField(
            model_name='ministre',
            name='presentation_accroche',
            field=models.TextField(blank=True, help_text='Phrase mise en avant en tête de présentation.', verbose_name='Présentation — accroche'),
        ),
        migrations.AddField(
            model_name='ministre',
            name='presentation_corps',
            field=models.TextField(blank=True, verbose_name='Présentation — corps'),
        ),
        migrations.AlterField(
            model_name='ministre',
            name='nom',
            field=models.CharField(default='Dr Maman Laouali ABDOU RAFA', max_length=200, verbose_name='Nom (carte accueil)'),
        ),
        migrations.CreateModel(
            name='MinistreParcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('formation', 'Formation'), ('professionnel', 'Parcours professionnel')], max_length=20, verbose_name='Catégorie')),
                ('periode', models.CharField(max_length=80, verbose_name='Période')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='Détail / Organisme')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('ministre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='ministere.ministre')),
            ],
            options={
                'verbose_name': 'Étape (formation / parcours)',
                'verbose_name_plural': 'Étapes (formation / parcours)',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MinistreRepere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(choices=[('cake', 'Gâteau (naissance)'), ('family', 'Famille'), ('translate', 'Langues'), ('school', 'Formation'), ('work', 'Travail'), ('place', 'Lieu')], default='place', max_length=40, verbose_name='Icône')),
                ('texte', models.CharField(max_length=255, verbose_name='Texte')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('ministre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reperes', to='ministere.ministre')),
            ],
            options={
                'verbose_name': 'Repère biographique',
                'verbose_name_plural': 'Repères biographiques',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
