# Generated by Django 6.0.6 on 2026-06-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministere', '0002_ministre_conseils_ministre_conseils_periode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('date', models.DateField(verbose_name='Date')),
                ('extrait', models.TextField(blank=True, verbose_name='Extrait')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='discours/', verbose_name='Fichier PDF')),
                ('lien', models.CharField(blank=True, help_text="Utilisé si aucun PDF n'est fourni (ex. vidéo).", max_length=300, verbose_name='Lien externe')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Discours',
                'verbose_name_plural': 'Discours',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MembreCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('fonction', models.CharField(max_length=200, verbose_name='Fonction')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cabinet/', verbose_name='Photo')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Membre du cabinet',
                'verbose_name_plural': 'Cabinet — membres',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
