# Generated by Django 6.0.6 on 2026-06-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministere', '0003_discours_membrecabinet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre / légende')),
                ('categorie', models.CharField(choices=[('Portraits', 'Portraits'), ('Activités', 'Activités'), ('Audiences', 'Audiences'), ('Cérémonies', 'Cérémonies')], default='Activités', max_length=40, verbose_name='Catégorie (onglet)')),
                ('image', models.ImageField(blank=True, help_text='Visuel officiel. Si vide, le champ « URL / chemin » est utilisé.', null=True, upload_to='album-ministre/', verbose_name='Photo')),
                ('image_url', models.CharField(blank=True, help_text="Utilisé si aucun fichier n'est téléversé. Ex. https://… ou /DrRafa.jpeg", max_length=500, verbose_name='Image — URL ou chemin')),
                ('date', models.DateField(blank=True, help_text='Mois affiché sous la photo (le jour est ignoré).', null=True, verbose_name='Date')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Photo de l'album",
                'verbose_name_plural': 'Album photo du Ministre',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
