# Generated by Django 6.0.6 on 2026-06-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministere', '0004_albumphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('type', models.CharField(choices=[('Conférence', 'Conférence'), ('Atelier', 'Atelier'), ('Réunion', 'Réunion'), ('Cérémonie', 'Cérémonie'), ('Mission', 'Mission'), ('Autre', 'Autre')], default='Autre', max_length=40, verbose_name='Type')),
                ('date_debut', models.DateField(verbose_name='Date (début)')),
                ('date_fin', models.DateField(blank=True, help_text="À renseigner seulement si l'événement dure plusieurs jours.", null=True, verbose_name='Date (fin)')),
                ('heure', models.CharField(blank=True, help_text='Ex. : « 09h00 » ou « 09h00 – 13h00 ».', max_length=40, verbose_name='Heure')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, help_text='Visuel. Si vide, le champ « URL / chemin » est utilisé.', null=True, upload_to='evenements/', verbose_name='Image')),
                ('image_url', models.CharField(blank=True, help_text="Utilisé si aucun fichier n'est téléversé.", max_length=500, verbose_name='Image — URL ou chemin')),
                ('lien', models.CharField(blank=True, max_length=300, verbose_name='Lien (détails / inscription)')),
                ('a_la_une', models.BooleanField(default=False, verbose_name='À la une')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut', '-id'],
            },
        ),
    ]
