# Generated by Django 6.0.6 on 2026-07-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministere', '0005_evenement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an', models.CharField(help_text='Ex. : « 1958 » ou « Depuis 2023 ».', max_length=40, verbose_name='Année')),
                ('nom', models.CharField(max_length=255, verbose_name='Dénomination')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Dénomination (historique)',
                'verbose_name_plural': 'Historique — dénominations',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MinistreHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('ministre', 'Ministre des Finances'), ('delegue', "Ministre délégué / Secrétaire d'État")], db_index=True, default='ministre', max_length=20, verbose_name='Catégorie')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='ministres/', verbose_name='Photo')),
                ('photo_url', models.CharField(blank=True, help_text="Utilisé si aucun fichier n'est téléversé.", max_length=500, verbose_name='Photo — URL ou chemin')),
                ('secours', models.URLField(blank=True, verbose_name='Image de secours (URL)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Ministre (historique)',
                'verbose_name_plural': 'Historique — ministres & délégués',
                'ordering': ['categorie', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TexteOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(verbose_name='Titre')),
                ('annee', models.CharField(blank=True, max_length=10, verbose_name='Année')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='textes/', verbose_name='Fichier PDF')),
                ('lien', models.CharField(blank=True, help_text="Utilisé si aucun PDF n'est téléversé. « # » par défaut.", max_length=400, verbose_name='Lien externe')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Texte portant organisation',
                'verbose_name_plural': 'Historique — textes portant organisation',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
