# Generated by Django 6.0.6 on 2026-07-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrique', models.CharField(choices=[('ministere', 'Publications du Ministère'), ('autres', 'Autres publications'), ('etats-financiers', 'États Financiers')], db_index=True, max_length=30, verbose_name='Rubrique')),
                ('type', models.CharField(help_text='Ex. : « Bulletin », « Arrêté », « 2020 »…', max_length=60, verbose_name='Type / étiquette')),
                ('titre', models.TextField(verbose_name='Titre')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='publications/', verbose_name='Fichier PDF')),
                ('lien', models.CharField(blank=True, help_text="Utilisé si aucun PDF n'est téléversé. « # » par défaut.", max_length=400, verbose_name='Lien externe')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['rubrique', 'ordre', 'id'],
            },
        ),
    ]
