# Generated by Django 6.0.6 on 2026-06-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicateurCle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('valeur', models.FloatField(verbose_name='Valeur (%)')),
                ('maximum', models.FloatField(default=100, verbose_name='Maximum de la jauge')),
                ('couleur', models.CharField(default='#2E8B57', max_length=7, verbose_name='Couleur')),
                ('note', models.CharField(blank=True, help_text='Ex. : « en % du PIB · 2025 ».', max_length=80, verbose_name='Note')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Indicateur clé (jauge)',
                'verbose_name_plural': 'Indicateurs — clés (jauges)',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IndicateurMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='Libellé')),
                ('valeur', models.FloatField(verbose_name='Valeur')),
                ('decimales', models.PositiveSmallIntegerField(default=0, help_text="Nombre de décimales à l'affichage.", verbose_name='Décimales')),
                ('suffixe', models.CharField(blank=True, help_text='Ex. : « % ».', max_length=10, verbose_name='Suffixe')),
                ('unite', models.CharField(blank=True, help_text='Ex. : « Milliards FCFA » ou « Mars 2026 ».', max_length=60, verbose_name='Unité / précision')),
                ('icone', models.CharField(choices=[('paid', 'Monnaie (PIB)'), ('trending_up', 'Croissance'), ('show_chart', 'Courbe (inflation)'), ('request_quote', 'Financement'), ('account_balance', 'Institution'), ('savings', 'Épargne')], default='paid', max_length=30, verbose_name='Icône')),
                ('couleur_debut', models.CharField(default='#0a5ca8', max_length=7, verbose_name='Couleur (début)')),
                ('couleur_fin', models.CharField(default='#002B55', max_length=7, verbose_name='Couleur (fin)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Grand indicateur',
                'verbose_name_plural': 'Indicateurs — grands (cartes)',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
