# Generated by Django 6.0.6 on 2026-06-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('rubrique', models.CharField(choices=[('Activités du Ministre', 'Activités du Ministre'), ('Événements', 'Événements'), ('Audiences & Rencontres', 'Audiences & Rencontres'), ('Communiqués', 'Communiqués'), ('Autre', 'Autre')], default='Activités du Ministre', max_length=60, verbose_name='Rubrique')),
                ('date', models.DateField(verbose_name='Date')),
                ('chapo', models.TextField(blank=True, help_text="Court résumé affiché sur la carte et en tête d'article.", verbose_name='Chapô (résumé)')),
                ('contenu', models.TextField(blank=True, help_text="Corps de l'article. Un paragraphe par ligne.", verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, help_text='Visuel. Si vide, le champ « URL / chemin » est utilisé.', null=True, upload_to='actualites/', verbose_name='Image')),
                ('image_url', models.CharField(blank=True, help_text="Utilisé si aucun fichier n'est téléversé.", max_length=500, verbose_name='Image — URL ou chemin')),
                ('a_la_une', models.BooleanField(default=False, verbose_name='À la une')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
