# Generated by Django 6.0.6 on 2026-07-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroRevue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(db_index=True, verbose_name='Année')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='revue-presse/', verbose_name='Fichier PDF')),
                ('lien', models.CharField(blank=True, help_text="Utilisé si aucun PDF n'est téléversé. « # » par défaut.", max_length=300, verbose_name='Lien externe')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Numéro de revue de presse',
                'verbose_name_plural': 'Revue de presse',
                'ordering': ['-annee', 'ordre', 'id'],
            },
        ),
    ]
