# Generated by Django 6.0.6 on 2026-07-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actualites', '0002_numerorevue'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='video_url',
            field=models.URLField(blank=True, help_text="Optionnel — YouTube/Vimeo ou fichier .mp4. Affichée à la place de l'image.", max_length=500, verbose_name='Vidéo (URL)'),
        ),
    ]
